print('calculo de tabuada ')
n=int(input('digita um número'))
print('#'*24)
print('{:2} vezes  1 igual a {:3}'.format(n, (n*1)))
print('{:2} vezes  2 igual a {:3}'.format(n, (n*2)))
print('{:2} vezes  3 igual a {:3}'.format(n, (n*3)))
print('{:2} vezes  4 igual a {:3}'.format(n, (n*4)))
print('{:2} vezes  5 igual a {:3}'.format(n, (n*5)))
print('{:2} vezes  6 igual a {:3}'.format(n, (n*6)))
print('{:2} vezes  7 igual a {:3}'.format(n, (n*7)))
print('{:2} vezes  8 igual a {:3}'.format(n, (n*8)))
print('{:2} vezes  9 igual a {:3}'.format(n, (n*9)))
print('{:2} vezes 10 igual a  {}'.format(n, (n*10)))
print('#'*24)